version: '3'

services:
  sqlserver:
    build: ./sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Strong!Password
      TZ: "Europe/Amsterdam"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/scripts:/scripts
