version: '3'

services:
  sqlserver:
    build: ./sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Strong!Password
      TZ: "Europe/Amsterdam"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/scripts:/scripts

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce'
