version: '2'

services:
  sqlserver:
    build: ./
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Strong!Password
      TZ: "Europe/Amsterdam"
    ports:
      - "1433:1433"
